spring.application.name=thymeleaf
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false


# Configuración H2
spring.datasource.url=jdbc:h2:mem:wikidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita la consola de H2 en http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Crea/Actualiza el esquema de la BD automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=update