spring.application.name=thymeleaf
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false


# Configuración H2
spring.datasource.url=jdbc:h2:mem:wikidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola y permitir frames (esto evita el 404/pantalla blanca)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Crea/Actualiza el esquema de la BD automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=update

# Forzar que la BD se mantenga activa entre conexiones
spring.datasource.url=jdbc:h2:mem:wikidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE